//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Celeste_Launcher_Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Celeste_Launcher_Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap add_folder_64 {
            get {
                object obj = ResourceManager.GetObject("add-folder-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap add_folder_64__g {
            get {
                object obj = ResourceManager.GetObject("add-folder-64 _g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AddFriends_Normal {
            get {
                object obj = ResourceManager.GetObject("AddFriends_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BackgroundTexture {
            get {
                object obj = ResourceManager.GetObject("BackgroundTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BarSeparator {
            get {
                object obj = ResourceManager.GetObject("BarSeparator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BarSeparatorVertical {
            get {
                object obj = ResourceManager.GetObject("BarSeparatorVertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CelesteWebsiteNormal {
            get {
                object obj = ResourceManager.GetObject("CelesteWebsiteNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap delete_64 {
            get {
                object obj = ResourceManager.GetObject("delete-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap delete_64_g {
            get {
                object obj = ResourceManager.GetObject("delete-64_g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap delete_64_gray {
            get {
                object obj = ResourceManager.GetObject("delete-64_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DialogBox {
            get {
                object obj = ResourceManager.GetObject("DialogBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DialogBoxSmall {
            get {
                object obj = ResourceManager.GetObject("DialogBoxSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap downloads_64 {
            get {
                object obj = ResourceManager.GetObject("downloads-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap downloads_64__g {
            get {
                object obj = ResourceManager.GetObject("downloads-64 _g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder_3_64 {
            get {
                object obj = ResourceManager.GetObject("folder-3-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder_3_64__g {
            get {
                object obj = ResourceManager.GetObject("folder-3-64 _g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder_3_64__g1 {
            get {
                object obj = ResourceManager.GetObject("folder-3-64 _g1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FriendRequests_Normal {
            get {
                object obj = ResourceManager.GetObject("FriendRequests_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FriendsHover {
            get {
                object obj = ResourceManager.GetObject("FriendsHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FriendsNormal {
            get {
                object obj = ResourceManager.GetObject("FriendsNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string GamePathSelectionBrowseBtn {
            get {
                return ResourceManager.GetString("GamePathSelectionBrowseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string GamePathSelectionScanBtn {
            get {
                return ResourceManager.GetString("GamePathSelectionScanBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a game scan to install/update/repair 
        ///Age of Empires Online - Celeste Fan Project.
        /// </summary>
        public static string GamePathSelectionTitle {
            get {
                return ResourceManager.GetString("GamePathSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string GameScannerDiscordLabel {
            get {
                return ResourceManager.GetString("GameScannerDiscordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch Notes.
        /// </summary>
        public static string GameScannerPatchNotesLabel {
            get {
                return ResourceManager.GetString("GameScannerPatchNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Scan.
        /// </summary>
        public static string GameScannerTitle {
            get {
                return ResourceManager.GetString("GameScannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap help_64 {
            get {
                object obj = ResourceManager.GetObject("help-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap help_64_g {
            get {
                object obj = ResourceManager.GetObject("help-64_g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon™.
        /// </summary>
        public static string LanguageComingSoonToolTip {
            get {
                return ResourceManager.GetString("LanguageComingSoonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed:.
        /// </summary>
        public static string LauncherInstalledVersionLabel {
            get {
                return ResourceManager.GetString("LauncherInstalledVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New:.
        /// </summary>
        public static string LauncherUpdateNewVersionLabel {
            get {
                return ResourceManager.GetString("LauncherUpdateNewVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Update.
        /// </summary>
        public static string LauncherUpdateTitle {
            get {
                return ResourceManager.GetString("LauncherUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string LauncherUpdateUpdateBtn {
            get {
                return ResourceManager.GetString("LauncherUpdateUpdateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-login.
        /// </summary>
        public static string LoginAutoLoginOption {
            get {
                return ResourceManager.GetString("LoginAutoLoginOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string LoginEmailField {
            get {
                return ResourceManager.GetString("LoginEmailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string LoginForgottenPassword {
            get {
                return ResourceManager.GetString("LoginForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LoginPasswordField {
            get {
                return ResourceManager.GetString("LoginPasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginPerformLoginBtn {
            get {
                return ResourceManager.GetString("LoginPerformLoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember password.
        /// </summary>
        public static string LoginRememberPasswordOption {
            get {
                return ResourceManager.GetString("LoginRememberPasswordOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LongOne {
            get {
                object obj = ResourceManager.GetObject("LongOne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string MainMenuCelesteSideMenuBtn {
            get {
                return ResourceManager.GetString("MainMenuCelesteSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string MainMenuDiscordSideMenuBtn {
            get {
                return ResourceManager.GetString("MainMenuDiscordSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string MainMenuDonateSideMenuBtn {
            get {
                return ResourceManager.GetString("MainMenuDonateSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainMenuGameSettingsBtn {
            get {
                return ResourceManager.GetString("MainMenuGameSettingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change game language.
        /// </summary>
        public static string MainMenuGameSettingsMenuChangeGameLanguage {
            get {
                return ResourceManager.GetString("MainMenuGameSettingsMenuChangeGameLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Steam game.
        /// </summary>
        public static string MainMenuGameSettingsMenuConvertToSteamGame {
            get {
                return ResourceManager.GetString("MainMenuGameSettingsMenuConvertToSteamGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable diagnostic mode.
        /// </summary>
        public static string MainMenuGameSettingsMenuDiagnosticsMode {
            get {
                return ResourceManager.GetString("MainMenuGameSettingsMenuDiagnosticsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall helper.
        /// </summary>
        public static string MainMenuGameSettingsMenuFirewallHelper {
            get {
                return ResourceManager.GetString("MainMenuGameSettingsMenuFirewallHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game scanner.
        /// </summary>
        public static string MainMenuGameSettingsMenuGameScanner {
            get {
                return ResourceManager.GetString("MainMenuGameSettingsMenuGameScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string MainMenuGameSettingsMenuLauncherUpdater {
            get {
                return ResourceManager.GetString("MainMenuGameSettingsMenuLauncherUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows features.
        /// </summary>
        public static string MainMenuGameSettingsMenuWindowsFeatures {
            get {
                return ResourceManager.GetString("MainMenuGameSettingsMenuWindowsFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string MainMenuLoginBtn {
            get {
                return ResourceManager.GetString("MainMenuLoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Offline.
        /// </summary>
        public static string MainMenuPlayOfflineBtn {
            get {
                return ResourceManager.GetString("MainMenuPlayOfflineBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reddit.
        /// </summary>
        public static string MainMenuRedditSideMenuBtn {
            get {
                return ResourceManager.GetString("MainMenuRedditSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string MainMenuRegisterBtn {
            get {
                return ResourceManager.GetString("MainMenuRegisterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string MainMenuYoutubeSideMenuBtn {
            get {
                return ResourceManager.GetString("MainMenuYoutubeSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Type.
        /// </summary>
        public static string MultiplayerSettingsConnectionTypeTitle {
            get {
                return ResourceManager.GetString("MultiplayerSettingsConnectionTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAN only.
        /// </summary>
        public static string MultiplayerSettingsLANCheckbox {
            get {
                return ResourceManager.GetString("MultiplayerSettingsLANCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual (protocol: UDP, port:1000).
        /// </summary>
        public static string MultiplayerSettingsManual {
            get {
                return ResourceManager.GetString("MultiplayerSettingsManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAT Punchthrough (default).
        /// </summary>
        public static string MultiplayerSettingsNatPunchthrough {
            get {
                return ResourceManager.GetString("MultiplayerSettingsNatPunchthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string MultiplayerSettingsOtherCheckbox {
            get {
                return ResourceManager.GetString("MultiplayerSettingsOtherCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Mapping (WAN).
        /// </summary>
        public static string MultiplayerSettingsPortMappingTitle {
            get {
                return ResourceManager.GetString("MultiplayerSettingsPortMappingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote IP:.
        /// </summary>
        public static string MultiplayerSettingsRemoteIPLabel {
            get {
                return ResourceManager.GetString("MultiplayerSettingsRemoteIPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MultiplayerSettingsSaveBtn {
            get {
                return ResourceManager.GetString("MultiplayerSettingsSaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPnP using open.nat.
        /// </summary>
        public static string MultiplayerSettingsUpnp {
            get {
                return ResourceManager.GetString("MultiplayerSettingsUpnp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAN.
        /// </summary>
        public static string MultiplayerSettingsWANCheckbox {
            get {
                return ResourceManager.GetString("MultiplayerSettingsWANCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string NetworkDeviceSelectorSaveBtn {
            get {
                return ResourceManager.GetString("NetworkDeviceSelectorSaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select network device.
        /// </summary>
        public static string NetworkDeviceSelectorTitle {
            get {
                return ResourceManager.GetString("NetworkDeviceSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string OptionNo {
            get {
                return ResourceManager.GetString("OptionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OptionOk {
            get {
                return ResourceManager.GetString("OptionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string OptionYes {
            get {
                return ResourceManager.GetString("OptionYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string OverviewAccountSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewAccountSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvP Info.
        /// </summary>
        public static string OverviewChampionModeInfoSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewChampionModeInfoSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string OverviewDiscordSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewDiscordSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string OverviewDonateSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewDonateSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string OverviewFriendsSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewFriendsSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Search.
        /// </summary>
        public static string OverviewItemSearchSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewItemSearchSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string OverviewLoginBtn {
            get {
                return ResourceManager.GetString("OverviewLoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch Notes.
        /// </summary>
        public static string OverviewPatchNotesSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewPatchNotesSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Offline.
        /// </summary>
        public static string OverviewPlayOfflineBtn {
            get {
                return ResourceManager.GetString("OverviewPlayOfflineBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reddit.
        /// </summary>
        public static string OverviewRedditSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewRedditSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios.
        /// </summary>
        public static string OverviewScenarioManagerSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewScenarioManagerSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string OverviewSettingsSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewSettingsSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game tools.
        /// </summary>
        public static string OverviewToolsBtnTooltip {
            get {
                return ResourceManager.GetString("OverviewToolsBtnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch.
        /// </summary>
        public static string OverviewTwitchSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewTwitchSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string OverviewWebsiteSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewWebsiteSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string OverviewYoutubeSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewYoutubeSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing ProcDump.
        /// </summary>
        public static string ProcDumpInstallerTitle {
            get {
                return ResourceManager.GetString("ProcDumpInstallerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RefreshHover {
            get {
                object obj = ResourceManager.GetObject("RefreshHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RefreshNormal {
            get {
                object obj = ResourceManager.GetObject("RefreshNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string RegisterCancelBtnText {
            get {
                return ResourceManager.GetString("RegisterCancelBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterCompleteRegistrationBtnText {
            get {
                return ResourceManager.GetString("RegisterCompleteRegistrationBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string RegisterEmailLabelText {
            get {
                return ResourceManager.GetString("RegisterEmailLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password:.
        /// </summary>
        public static string RegisterPasswordConfirmationLabelText {
            get {
                return ResourceManager.GetString("RegisterPasswordConfirmationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string RegisterPasswordLabelText {
            get {
                return ResourceManager.GetString("RegisterPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string RegisterResendBtnText {
            get {
                return ResourceManager.GetString("RegisterResendBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string RegisterUsernameLabelText {
            get {
                return ResourceManager.GetString("RegisterUsernameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string RegisterVerifyBtnText {
            get {
                return ResourceManager.GetString("RegisterVerifyBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify key:.
        /// </summary>
        public static string RegisterVerifyLabelText {
            get {
                return ResourceManager.GetString("RegisterVerifyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ResetPasswordConfirmBtn {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ResetPasswordConfirmNewPassword {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string ResetPasswordCurrentPassword {
            get {
                return ResourceManager.GetString("ResetPasswordCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address:.
        /// </summary>
        public static string ResetPasswordEmailAddressField {
            get {
                return ResourceManager.GetString("ResetPasswordEmailAddressField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string ResetPasswordNewPassword {
            get {
                return ResourceManager.GetString("ResetPasswordNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPasswordResetBtn {
            get {
                return ResourceManager.GetString("ResetPasswordResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset key:.
        /// </summary>
        public static string ResetPasswordResetKeyField {
            get {
                return ResourceManager.GetString("ResetPasswordResetKeyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send reset key.
        /// </summary>
        public static string ResetPasswordSendResetBtn {
            get {
                return ResourceManager.GetString("ResetPasswordSendResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add scenario.
        /// </summary>
        public static string ScenarioManagerAddScenarioTooltip {
            get {
                return ResourceManager.GetString("ScenarioManagerAddScenarioTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download scenarios.
        /// </summary>
        public static string ScenarioManagerDownloadScenarioTooltip {
            get {
                return ResourceManager.GetString("ScenarioManagerDownloadScenarioTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ScenarioManagerOpenHelpTooltip {
            get {
                return ResourceManager.GetString("ScenarioManagerOpenHelpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open scenario directory in File Explorer.
        /// </summary>
        public static string ScenarioManagerOpenScenarioDirectoryTooltip {
            get {
                return ResourceManager.GetString("ScenarioManagerOpenScenarioDirectoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Scenario.
        /// </summary>
        public static string ScenarioManagerPlayScenarioBtn {
            get {
                return ResourceManager.GetString("ScenarioManagerPlayScenarioBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected scenario.
        /// </summary>
        public static string ScenarioManagerRemoveScenarioTooltip {
            get {
                return ResourceManager.GetString("ScenarioManagerRemoveScenarioTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Manager.
        /// </summary>
        public static string ScenarioManagerTitle {
            get {
                return ResourceManager.GetString("ScenarioManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string SteamConverterConfirmBtn {
            get {
                return ResourceManager.GetString("SteamConverterConfirmBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you want to start Celeste Fan Project Launcher when Age of Empires Online is started through Steam.
        /// </summary>
        public static string SteamConverterTitle {
            get {
                return ResourceManager.GetString("SteamConverterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string WindowsFeatureHelperEnableBtn {
            get {
                return ResourceManager.GetString("WindowsFeatureHelperEnableBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string WindowsFeatureHelperEnabledStatus {
            get {
                return ResourceManager.GetString("WindowsFeatureHelperEnabledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enabled.
        /// </summary>
        public static string WindowsFeatureHelperNotEnabledStatus {
            get {
                return ResourceManager.GetString("WindowsFeatureHelperNotEnabledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Feature Helper.
        /// </summary>
        public static string WindowsFeatureHelperTitle {
            get {
                return ResourceManager.GetString("WindowsFeatureHelperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string WindowsFeatureHelperUnknownStatus {
            get {
                return ResourceManager.GetString("WindowsFeatureHelperUnknownStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string WindowsFirewallHelperApplication {
            get {
                return ResourceManager.GetString("WindowsFirewallHelperApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound.
        /// </summary>
        public static string WindowsFirewallHelperInbound {
            get {
                return ResourceManager.GetString("WindowsFirewallHelperInbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string WindowsFirewallHelperOpenBtn {
            get {
                return ResourceManager.GetString("WindowsFirewallHelperOpenBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbound.
        /// </summary>
        public static string WindowsFirewallHelperOutbound {
            get {
                return ResourceManager.GetString("WindowsFirewallHelperOutbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Firewall Helper.
        /// </summary>
        public static string WindowsFirewallHelperTitle {
            get {
                return ResourceManager.GetString("WindowsFirewallHelperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap XButton_Hover {
            get {
                object obj = ResourceManager.GetObject("XButton_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap XButton_Normal {
            get {
                object obj = ResourceManager.GetObject("XButton_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
