//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Celeste_Launcher_Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Celeste_Launcher_Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not perform auto-signin due to an unexpected error.
        /// </summary>
        public static string AutoLoginError {
            get {
                return ResourceManager.GetString("AutoLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not perform auto-signin, please sign in again manually.
        /// </summary>
        public static string AutoLoginFailed {
            get {
                return ResourceManager.GetString("AutoLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while changing password:.
        /// </summary>
        public static string ChangePasswordError {
            get {
                return ResourceManager.GetString("ChangePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password must be at least 8 characters and maximum 32 characters..
        /// </summary>
        public static string ChangePasswordInvalidLength {
            get {
                return ResourceManager.GetString("ChangePasswordInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password, character &apos; and &quot; are not allowed!.
        /// </summary>
        public static string ChangePasswordInvalidPassword {
            get {
                return ResourceManager.GetString("ChangePasswordInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmed password does not match..
        /// </summary>
        public static string ChangePasswordMismatch {
            get {
                return ResourceManager.GetString("ChangePasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password must be different from the old..
        /// </summary>
        public static string ChangePasswordSamePassword {
            get {
                return ResourceManager.GetString("ChangePasswordSamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully changed..
        /// </summary>
        public static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ally.
        /// </summary>
        public static string ColorPickerAlly {
            get {
                return ResourceManager.GetString("ColorPickerAlly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string ColorPickerBlue {
            get {
                return ResourceManager.GetString("ColorPickerBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue (self).
        /// </summary>
        public static string ColorPickerBlueSelf {
            get {
                return ResourceManager.GetString("ColorPickerBlueSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        public static string ColorPickerCyan {
            get {
                return ResourceManager.GetString("ColorPickerCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ColorPickerDefault {
            get {
                return ResourceManager.GetString("ColorPickerDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foe.
        /// </summary>
        public static string ColorPickerFoe {
            get {
                return ResourceManager.GetString("ColorPickerFoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend or foe colors.
        /// </summary>
        public static string ColorPickerFriendOrFoeTitle {
            get {
                return ResourceManager.GetString("ColorPickerFriendOrFoeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first do a game scan before changing colors..
        /// </summary>
        public static string ColorPickerGamePathNotYetSet {
            get {
                return ResourceManager.GetString("ColorPickerGamePathNotYetSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string ColorPickerGreen {
            get {
                return ResourceManager.GetString("ColorPickerGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string ColorPickerOrange {
            get {
                return ResourceManager.GetString("ColorPickerOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string ColorPickerPink {
            get {
                return ResourceManager.GetString("ColorPickerPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 1.
        /// </summary>
        public static string ColorPickerPlayer1 {
            get {
                return ResourceManager.GetString("ColorPickerPlayer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 2.
        /// </summary>
        public static string ColorPickerPlayer2 {
            get {
                return ResourceManager.GetString("ColorPickerPlayer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 3.
        /// </summary>
        public static string ColorPickerPlayer3 {
            get {
                return ResourceManager.GetString("ColorPickerPlayer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 4.
        /// </summary>
        public static string ColorPickerPlayer4 {
            get {
                return ResourceManager.GetString("ColorPickerPlayer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 5.
        /// </summary>
        public static string ColorPickerPlayer5 {
            get {
                return ResourceManager.GetString("ColorPickerPlayer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 6.
        /// </summary>
        public static string ColorPickerPlayer6 {
            get {
                return ResourceManager.GetString("ColorPickerPlayer6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 7.
        /// </summary>
        public static string ColorPickerPlayer7 {
            get {
                return ResourceManager.GetString("ColorPickerPlayer7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 8.
        /// </summary>
        public static string ColorPickerPlayer8 {
            get {
                return ResourceManager.GetString("ColorPickerPlayer8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player colors.
        /// </summary>
        public static string ColorPickerPlayerColorTitle {
            get {
                return ResourceManager.GetString("ColorPickerPlayerColorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string ColorPickerPurple {
            get {
                return ResourceManager.GetString("ColorPickerPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string ColorPickerRed {
            get {
                return ResourceManager.GetString("ColorPickerRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red (foe).
        /// </summary>
        public static string ColorPickerRedFoe {
            get {
                return ResourceManager.GetString("ColorPickerRedFoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ColorPickerSaveBtn {
            get {
                return ResourceManager.GetString("ColorPickerSaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        public static string ColorPickerSelf {
            get {
                return ResourceManager.GetString("ColorPickerSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string ColorPickerTitleColor {
            get {
                return ResourceManager.GetString("ColorPickerTitleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picker.
        /// </summary>
        public static string ColorPickerTitlePicker {
            get {
                return ResourceManager.GetString("ColorPickerTitlePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Picker.
        /// </summary>
        public static string ColorPickerWindowTitle {
            get {
                return ResourceManager.GetString("ColorPickerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string ColorPickerYellow {
            get {
                return ResourceManager.GetString("ColorPickerYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow (ally).
        /// </summary>
        public static string ColorPickerYellowAlly {
            get {
                return ResourceManager.GetString("ColorPickerYellowAlly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while starting diagnostics mode. Please try again or check the log files..
        /// </summary>
        public static string DiagnosticsModeError {
            get {
                return ResourceManager.GetString("DiagnosticsModeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics mode requires ProcDump to be installed which was not found. Diagnostics mode will therefore be disabled..
        /// </summary>
        public static string DiagnosticsModeMissingProcdump {
            get {
                return ResourceManager.GetString("DiagnosticsModeMissingProcdump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Core Limit has been Disabled..
        /// </summary>
        public static string DisableLimitCPUCores {
            get {
                return ResourceManager.GetString("DisableLimitCPUCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcDump.exe need to be installed first. Would you like to install it now?.
        /// </summary>
        public static string EnableDiagnosticsModeInstallProcdumpPrompt {
            get {
                return ResourceManager.GetString("EnableDiagnosticsModeInstallProcdumpPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enable &quot;Diagnostic Mode&quot;. Error message:.
        /// </summary>
        public static string EnableDiagnosticsModeProcdumpInstallError {
            get {
                return ResourceManager.GetString("EnableDiagnosticsModeProcdumpInstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Core Limit has been Enabled..
        /// </summary>
        public static string EnableLimitCPUCores {
            get {
                return ResourceManager.GetString("EnableLimitCPUCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string FriendListAcceptRequestBtn {
            get {
                return ResourceManager.GetString("FriendListAcceptRequestBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friend.
        /// </summary>
        public static string FriendListAddFriendBtn {
            get {
                return ResourceManager.GetString("FriendListAddFriendBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel friend request.
        /// </summary>
        public static string FriendListCancelFriendRequest {
            get {
                return ResourceManager.GetString("FriendListCancelFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string FriendListDeclineRequestBtn {
            get {
                return ResourceManager.GetString("FriendListDeclineRequestBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FriendListFilterPlaceholder {
            get {
                return ResourceManager.GetString("FriendListFilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has sent you a friend request.
        /// </summary>
        public static string FriendListFriendRequestDescription {
            get {
                return ResourceManager.GetString("FriendListFriendRequestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a friend because your friendlist is full..
        /// </summary>
        public static string FriendListMaxFriendsReached {
            get {
                return ResourceManager.GetString("FriendListMaxFriendsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string FriendListOffline {
            get {
                return ResourceManager.GetString("FriendListOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing friend request.
        /// </summary>
        public static string FriendListOutgoingFriendRequest {
            get {
                return ResourceManager.GetString("FriendListOutgoingFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove friend.
        /// </summary>
        public static string FriendListRemoveFriend {
            get {
                return ResourceManager.GetString("FriendListRemoveFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string FriendListTitle {
            get {
                return ResourceManager.GetString("FriendListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends online:.
        /// </summary>
        public static string FriendsOnlineText {
            get {
                return ResourceManager.GetString("FriendsOnlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is still running, please close it and try again..
        /// </summary>
        public static string GameAlreadyRunningError {
            get {
                return ResourceManager.GetString("GameAlreadyRunningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected game path does not exist.
        /// </summary>
        public static string GamePathInvalidPath {
            get {
                return ResourceManager.GetString("GamePathInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string GamePathSelectionBrowseBtn {
            get {
                return ResourceManager.GetString("GamePathSelectionBrowseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string GamePathSelectionScanBtn {
            get {
                return ResourceManager.GetString("GamePathSelectionScanBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a game scan to install/update/repair 
        ///Age of Empires Online - Celeste Fan Project.
        /// </summary>
        public static string GamePathSelectionTitle {
            get {
                return ResourceManager.GetString("GamePathSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select game location.
        /// </summary>
        public static string GamePathSelectionWindowTitle {
            get {
                return ResourceManager.GetString("GamePathSelectionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select location of Spartan.exe (Age of Empires Online).
        /// </summary>
        public static string GamePathSelectorTitle {
            get {
                return ResourceManager.GetString("GamePathSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game scan failed..
        /// </summary>
        public static string GameScannerDidNotPass {
            get {
                return ResourceManager.GetString("GameScannerDidNotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of your game files are outdated. Would you like to run a &apos;Game Scan&apos; to update these files?.
        /// </summary>
        public static string GameScannerDidNotPassQuickScan {
            get {
                return ResourceManager.GetString("GameScannerDidNotPassQuickScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string GameScannerDiscordLabel {
            get {
                return ResourceManager.GetString("GameScannerDiscordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string GameScannerDoneLabel {
            get {
                return ResourceManager.GetString("GameScannerDoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game scan has successfully completed.
        /// </summary>
        public static string GameScannerDoneMessage {
            get {
                return ResourceManager.GetString("GameScannerDoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string GameScannerDownloading {
            get {
                return ResourceManager.GetString("GameScannerDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting download.
        /// </summary>
        public static string GameScannerDownloadStarting {
            get {
                return ResourceManager.GetString("GameScannerDownloadStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting downloaded file.
        /// </summary>
        public static string GameScannerExtracting {
            get {
                return ResourceManager.GetString("GameScannerExtracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while running the game scan. Please try again or check the log files..
        /// </summary>
        public static string GameScannerFailed {
            get {
                return ResourceManager.GetString("GameScannerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast download.
        /// </summary>
        public static string GameScannerFastDownloadOption {
            get {
                return ResourceManager.GetString("GameScannerFastDownloadOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling fast downloads might cause issues downloading game data. If it fails downloading your game files, try again with this option disabled..
        /// </summary>
        public static string GameScannerFastDownloadWarning {
            get {
                return ResourceManager.GetString("GameScannerFastDownloadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizing.
        /// </summary>
        public static string GameScannerFinalizing {
            get {
                return ResourceManager.GetString("GameScannerFinalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch Notes.
        /// </summary>
        public static string GameScannerPatchNotesLabel {
            get {
                return ResourceManager.GetString("GameScannerPatchNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game scanner encountered an unexpected problem. Please try again or check the log files..
        /// </summary>
        public static string GameScannerScanError {
            get {
                return ResourceManager.GetString("GameScannerScanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate Spartan.exe, please run a game scan to make sure you are not missing any game files..
        /// </summary>
        public static string GameScannerSpartanNotFound {
            get {
                return ResourceManager.GetString("GameScannerSpartanNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Scan.
        /// </summary>
        public static string GameScannerTitle {
            get {
                return ResourceManager.GetString("GameScannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying file integrity.
        /// </summary>
        public static string GameScannerVerifying {
            get {
                return ResourceManager.GetString("GameScannerVerifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking downloaded file.
        /// </summary>
        public static string GameScannerVerifyingDownloadedFile {
            get {
                return ResourceManager.GetString("GameScannerVerifyingDownloadedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking extracted file.
        /// </summary>
        public static string GameScannerVerifyingExtractedFile {
            get {
                return ResourceManager.GetString("GameScannerVerifyingExtractedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again or check the log files..
        /// </summary>
        public static string GenericUnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("GenericUnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The launcher cannot be started from {0} because it is not allowed to write files here. Please install your launcher in a directory under &quot;Documents&quot; or a location where it is allowed to write files..
        /// </summary>
        public static string InstallationPathForbidden {
            get {
                return ResourceManager.GetString("InstallationPathForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon™.
        /// </summary>
        public static string LanguageComingSoonToolTip {
            get {
                return ResourceManager.GetString("LanguageComingSoonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The launcher is already running and will now exit..
        /// </summary>
        public static string LauncherAlreadyRunningMessage {
            get {
                return ResourceManager.GetString("LauncherAlreadyRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed:.
        /// </summary>
        public static string LauncherInstalledVersionLabel {
            get {
                return ResourceManager.GetString("LauncherInstalledVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New:.
        /// </summary>
        public static string LauncherUpdateNewVersionLabel {
            get {
                return ResourceManager.GetString("LauncherUpdateNewVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while performing the update. The application will now close. If this problem continues, try and update manually..
        /// </summary>
        public static string LauncherUpdaterError {
            get {
                return ResourceManager.GetString("LauncherUpdaterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celeste Fan Project Launcher has been updated and will now re-start..
        /// </summary>
        public static string LauncherUpdaterUpdateSuccess {
            get {
                return ResourceManager.GetString("LauncherUpdaterUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Update.
        /// </summary>
        public static string LauncherUpdateTitle {
            get {
                return ResourceManager.GetString("LauncherUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string LauncherUpdateUpdateBtn {
            get {
                return ResourceManager.GetString("LauncherUpdateUpdateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-login.
        /// </summary>
        public static string LoginAutoLoginOption {
            get {
                return ResourceManager.GetString("LoginAutoLoginOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered email address is not a valid email address..
        /// </summary>
        public static string LoginBadEmail {
            get {
                return ResourceManager.GetString("LoginBadEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string LoginEmailField {
            get {
                return ResourceManager.GetString("LoginEmailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed logging in:.
        /// </summary>
        public static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string LoginForgottenPassword {
            get {
                return ResourceManager.GetString("LoginForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LoginPasswordField {
            get {
                return ResourceManager.GetString("LoginPasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginPerformLoginBtn {
            get {
                return ResourceManager.GetString("LoginPerformLoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember password.
        /// </summary>
        public static string LoginRememberPasswordOption {
            get {
                return ResourceManager.GetString("LoginRememberPasswordOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered password has to be maximum 32 characters..
        /// </summary>
        public static string LoginTooLongPassword {
            get {
                return ResourceManager.GetString("LoginTooLongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered password has to be at least 8 characters..
        /// </summary>
        public static string LoginTooShortPassword {
            get {
                return ResourceManager.GetString("LoginTooShortPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string MainMenuCelesteSideMenuBtn {
            get {
                return ResourceManager.GetString("MainMenuCelesteSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string MainMenuDiscordSideMenuBtn {
            get {
                return ResourceManager.GetString("MainMenuDiscordSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string MainMenuDonateSideMenuBtn {
            get {
                return ResourceManager.GetString("MainMenuDonateSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainMenuGameSettingsBtn {
            get {
                return ResourceManager.GetString("MainMenuGameSettingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change game language.
        /// </summary>
        public static string MainMenuGameSettingsMenuChangeGameLanguage {
            get {
                return ResourceManager.GetString("MainMenuGameSettingsMenuChangeGameLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Steam game.
        /// </summary>
        public static string MainMenuGameSettingsMenuConvertToSteamGame {
            get {
                return ResourceManager.GetString("MainMenuGameSettingsMenuConvertToSteamGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable diagnostic mode.
        /// </summary>
        public static string MainMenuGameSettingsMenuDiagnosticsMode {
            get {
                return ResourceManager.GetString("MainMenuGameSettingsMenuDiagnosticsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall helper.
        /// </summary>
        public static string MainMenuGameSettingsMenuFirewallHelper {
            get {
                return ResourceManager.GetString("MainMenuGameSettingsMenuFirewallHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game scanner.
        /// </summary>
        public static string MainMenuGameSettingsMenuGameScanner {
            get {
                return ResourceManager.GetString("MainMenuGameSettingsMenuGameScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string MainMenuGameSettingsMenuLauncherUpdater {
            get {
                return ResourceManager.GetString("MainMenuGameSettingsMenuLauncherUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows features.
        /// </summary>
        public static string MainMenuGameSettingsMenuWindowsFeatures {
            get {
                return ResourceManager.GetString("MainMenuGameSettingsMenuWindowsFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string MainMenuLoginBtn {
            get {
                return ResourceManager.GetString("MainMenuLoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Offline.
        /// </summary>
        public static string MainMenuPlayOfflineBtn {
            get {
                return ResourceManager.GetString("MainMenuPlayOfflineBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reddit.
        /// </summary>
        public static string MainMenuRedditSideMenuBtn {
            get {
                return ResourceManager.GetString("MainMenuRedditSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string MainMenuRegisterBtn {
            get {
                return ResourceManager.GetString("MainMenuRegisterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string MainMenuYoutubeSideMenuBtn {
            get {
                return ResourceManager.GetString("MainMenuYoutubeSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Type.
        /// </summary>
        public static string MultiplayerSettingsConnectionTypeTitle {
            get {
                return ResourceManager.GetString("MultiplayerSettingsConnectionTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAN only.
        /// </summary>
        public static string MultiplayerSettingsLANCheckbox {
            get {
                return ResourceManager.GetString("MultiplayerSettingsLANCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual (protocol: UDP, port:1000).
        /// </summary>
        public static string MultiplayerSettingsManual {
            get {
                return ResourceManager.GetString("MultiplayerSettingsManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAT Punchthrough (default).
        /// </summary>
        public static string MultiplayerSettingsNatPunchthrough {
            get {
                return ResourceManager.GetString("MultiplayerSettingsNatPunchthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string MultiplayerSettingsOtherCheckbox {
            get {
                return ResourceManager.GetString("MultiplayerSettingsOtherCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string MultiplayerSettingsOtherNetworkDevice {
            get {
                return ResourceManager.GetString("MultiplayerSettingsOtherNetworkDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Mapping (WAN).
        /// </summary>
        public static string MultiplayerSettingsPortMappingTitle {
            get {
                return ResourceManager.GetString("MultiplayerSettingsPortMappingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote IP:.
        /// </summary>
        public static string MultiplayerSettingsRemoteIPLabel {
            get {
                return ResourceManager.GetString("MultiplayerSettingsRemoteIPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MultiplayerSettingsSaveBtn {
            get {
                return ResourceManager.GetString("MultiplayerSettingsSaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer Settings.
        /// </summary>
        public static string MultiplayerSettingsTitle {
            get {
                return ResourceManager.GetString("MultiplayerSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPnP using open.nat.
        /// </summary>
        public static string MultiplayerSettingsUpnp {
            get {
                return ResourceManager.GetString("MultiplayerSettingsUpnp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAN.
        /// </summary>
        public static string MultiplayerSettingsWANCheckbox {
            get {
                return ResourceManager.GetString("MultiplayerSettingsWANCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a network interface.
        /// </summary>
        public static string NetworkDeviceSelectorNoDeviceSelected {
            get {
                return ResourceManager.GetString("NetworkDeviceSelectorNoDeviceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string NetworkDeviceSelectorSaveBtn {
            get {
                return ResourceManager.GetString("NetworkDeviceSelectorSaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select network device.
        /// </summary>
        public static string NetworkDeviceSelectorTitle {
            get {
                return ResourceManager.GetString("NetworkDeviceSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string OptionNo {
            get {
                return ResourceManager.GetString("OptionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OptionOk {
            get {
                return ResourceManager.GetString("OptionOk", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Log.
        /// </summary>
        public static string OptionOpenLog {
            get {
                return ResourceManager.GetString("OptionOpenLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string OptionYes {
            get {
                return ResourceManager.GetString("OptionYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string OverviewAccountSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewAccountSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvP Info.
        /// </summary>
        public static string OverviewChampionModeInfoSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewChampionModeInfoSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string OverviewChangePassword {
            get {
                return ResourceManager.GetString("OverviewChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string OverviewDiscordSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewDiscordSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string OverviewDonateSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewDonateSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable diagnostics mode.
        /// </summary>
        public static string OverviewEnableDiagnosticsMode {
            get {
                return ResourceManager.GetString("OverviewEnableDiagnosticsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit CPU Cores.
        /// </summary>
        public static string OverviewEnableLimitCPUCores {
            get {
                return ResourceManager.GetString("OverviewEnableLimitCPUCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string OverviewFriendsSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewFriendsSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game language.
        /// </summary>
        public static string OverviewGameLanguageSettings {
            get {
                return ResourceManager.GetString("OverviewGameLanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game scan.
        /// </summary>
        public static string OverviewGameScan {
            get {
                return ResourceManager.GetString("OverviewGameScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game settings.
        /// </summary>
        public static string OverviewGameSettings {
            get {
                return ResourceManager.GetString("OverviewGameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Search.
        /// </summary>
        public static string OverviewItemSearchSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewItemSearchSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string OverviewLoginBtn {
            get {
                return ResourceManager.GetString("OverviewLoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string OverviewLogOut {
            get {
                return ResourceManager.GetString("OverviewLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer settings.
        /// </summary>
        public static string OverviewMultiplayerSettings {
            get {
                return ResourceManager.GetString("OverviewMultiplayerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch Notes.
        /// </summary>
        public static string OverviewPatchNotesSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewPatchNotesSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player colors.
        /// </summary>
        public static string OverviewPlayerColors {
            get {
                return ResourceManager.GetString("OverviewPlayerColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Offline.
        /// </summary>
        public static string OverviewPlayOfflineBtn {
            get {
                return ResourceManager.GetString("OverviewPlayOfflineBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reddit.
        /// </summary>
        public static string OverviewRedditSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewRedditSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios.
        /// </summary>
        public static string OverviewScenarioManagerSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewScenarioManagerSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string OverviewSettingsSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewSettingsSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Steam game.
        /// </summary>
        public static string OverviewSteam {
            get {
                return ResourceManager.GetString("OverviewSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game tools.
        /// </summary>
        public static string OverviewToolsBtnTooltip {
            get {
                return ResourceManager.GetString("OverviewToolsBtnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch.
        /// </summary>
        public static string OverviewTwitchSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewTwitchSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update launcher.
        /// </summary>
        public static string OverviewUpdateLauncher {
            get {
                return ResourceManager.GetString("OverviewUpdateLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string OverviewWebsiteSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewWebsiteSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Features.
        /// </summary>
        public static string OverviewWindowsFeatures {
            get {
                return ResourceManager.GetString("OverviewWindowsFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Firewall.
        /// </summary>
        public static string OverviewWindowsFirewall {
            get {
                return ResourceManager.GetString("OverviewWindowsFirewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string OverviewYoutubeSideMenuBtn {
            get {
                return ResourceManager.GetString("OverviewYoutubeSideMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while installing ProcDump. Please try again or check the log files..
        /// </summary>
        public static string ProcdumpInstallError {
            get {
                return ResourceManager.GetString("ProcdumpInstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing ProcDump.
        /// </summary>
        public static string ProcDumpInstallerTitle {
            get {
                return ResourceManager.GetString("ProcDumpInstallerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string RegisterCancelBtnText {
            get {
                return ResourceManager.GetString("RegisterCancelBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterCompleteRegistrationBtnText {
            get {
                return ResourceManager.GetString("RegisterCompleteRegistrationBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string RegisterEmailLabelText {
            get {
                return ResourceManager.GetString("RegisterEmailLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while registering:.
        /// </summary>
        public static string RegisterError {
            get {
                return ResourceManager.GetString("RegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered email address is not a valid email address..
        /// </summary>
        public static string RegisterInvalidEmail {
            get {
                return ResourceManager.GetString("RegisterInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key you entered is not valid..
        /// </summary>
        public static string RegisterInvalidKeyLength {
            get {
                return ResourceManager.GetString("RegisterInvalidKeyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password, character &apos; and &quot; are not allowed!.
        /// </summary>
        public static string RegisterInvalidPassword {
            get {
                return ResourceManager.GetString("RegisterInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must be between 8 and 32 characters in length..
        /// </summary>
        public static string RegisterInvalidPasswordLength {
            get {
                return ResourceManager.GetString("RegisterInvalidPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username, only letters and digits allowed, minimum length is 3 char and maximum length is 15 characters..
        /// </summary>
        public static string RegisterInvalidUsername {
            get {
                return ResourceManager.GetString("RegisterInvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password:.
        /// </summary>
        public static string RegisterPasswordConfirmationLabelText {
            get {
                return ResourceManager.GetString("RegisterPasswordConfirmationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string RegisterPasswordLabelText {
            get {
                return ResourceManager.GetString("RegisterPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmed password must match the first password.
        /// </summary>
        public static string RegisterPasswordMismatch {
            get {
                return ResourceManager.GetString("RegisterPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string RegisterResendBtnText {
            get {
                return ResourceManager.GetString("RegisterResendBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string RegisterUsernameLabelText {
            get {
                return ResourceManager.GetString("RegisterUsernameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string RegisterVerifyBtnText {
            get {
                return ResourceManager.GetString("RegisterVerifyBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify key:.
        /// </summary>
        public static string RegisterVerifyLabelText {
            get {
                return ResourceManager.GetString("RegisterVerifyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ResetPasswordConfirmBtn {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ResetPasswordConfirmNewPassword {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string ResetPasswordCurrentPassword {
            get {
                return ResourceManager.GetString("ResetPasswordCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address:.
        /// </summary>
        public static string ResetPasswordEmailAddressField {
            get {
                return ResourceManager.GetString("ResetPasswordEmailAddressField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while resetting the password. Please try again or check the log files..
        /// </summary>
        public static string ResetPasswordError {
            get {
                return ResourceManager.GetString("ResetPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed resetting the password due to the following reason:.
        /// </summary>
        public static string ResetPasswordFailed {
            get {
                return ResourceManager.GetString("ResetPasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered email address is not a valid email address..
        /// </summary>
        public static string ResetPasswordInvalidEmail {
            get {
                return ResourceManager.GetString("ResetPasswordInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered key is not valid..
        /// </summary>
        public static string ResetPasswordInvalidKey {
            get {
                return ResourceManager.GetString("ResetPasswordInvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string ResetPasswordNewPassword {
            get {
                return ResourceManager.GetString("ResetPasswordNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPasswordResetBtn {
            get {
                return ResourceManager.GetString("ResetPasswordResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset key:.
        /// </summary>
        public static string ResetPasswordResetKeyField {
            get {
                return ResourceManager.GetString("ResetPasswordResetKeyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send reset key.
        /// </summary>
        public static string ResetPasswordSendResetBtn {
            get {
                return ResourceManager.GetString("ResetPasswordSendResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPasswordWindowTitle {
            get {
                return ResourceManager.GetString("ResetPasswordWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the file {0}?.
        /// </summary>
        public static string ScenarioEditorDeleteScenarioPrompt {
            get {
                return ResourceManager.GetString("ScenarioEditorDeleteScenarioPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario files.
        /// </summary>
        public static string ScenarioEditorFilePickerFileTypes {
            get {
                return ResourceManager.GetString("ScenarioEditorFilePickerFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Scenario File.
        /// </summary>
        public static string ScenarioEditorFilePickerTitle {
            get {
                return ResourceManager.GetString("ScenarioEditorFilePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} already exists, overwrite it?.
        /// </summary>
        public static string ScenarioEditorOverwritePrompt {
            get {
                return ResourceManager.GetString("ScenarioEditorOverwritePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add scenario.
        /// </summary>
        public static string ScenarioManagerAddScenarioTooltip {
            get {
                return ResourceManager.GetString("ScenarioManagerAddScenarioTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download scenarios.
        /// </summary>
        public static string ScenarioManagerDownloadScenarioTooltip {
            get {
                return ResourceManager.GetString("ScenarioManagerDownloadScenarioTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ScenarioManagerOpenHelpTooltip {
            get {
                return ResourceManager.GetString("ScenarioManagerOpenHelpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open scenario directory in File Explorer.
        /// </summary>
        public static string ScenarioManagerOpenScenarioDirectoryTooltip {
            get {
                return ResourceManager.GetString("ScenarioManagerOpenScenarioDirectoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Scenario.
        /// </summary>
        public static string ScenarioManagerPlayScenarioBtn {
            get {
                return ResourceManager.GetString("ScenarioManagerPlayScenarioBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected scenario.
        /// </summary>
        public static string ScenarioManagerRemoveScenarioTooltip {
            get {
                return ResourceManager.GetString("ScenarioManagerRemoveScenarioTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Manager.
        /// </summary>
        public static string ScenarioManagerTitle {
            get {
                return ResourceManager.GetString("ScenarioManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SendFriendRequestCancelBtn {
            get {
                return ResourceManager.GetString("SendFriendRequestCancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send a friend request to {0}.
        /// </summary>
        public static string SendFriendRequestFailed {
            get {
                return ResourceManager.GetString("SendFriendRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendFriendRequestSendBtn {
            get {
                return ResourceManager.GetString("SendFriendRequestSendBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a friend request.
        /// </summary>
        public static string SendFriendRequestTitle {
            get {
                return ResourceManager.GetString("SendFriendRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string SendFriendRequestUsernameLabel {
            get {
                return ResourceManager.GetString("SendFriendRequestUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is banned..
        /// </summary>
        public static string ServerResponse_ACCOUNT_BANNED {
            get {
                return ResourceManager.GetString("ServerResponse_ACCOUNT_BANNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already friends with this user..
        /// </summary>
        public static string ServerResponse_ALREADY_A_FRIEND {
            get {
                return ResourceManager.GetString("ServerResponse_ALREADY_A_FRIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already received a friend request from this user..
        /// </summary>
        public static string ServerResponse_ALREADY_RECEIVED_A_FRIEND_REQUEST {
            get {
                return ResourceManager.GetString("ServerResponse_ALREADY_RECEIVED_A_FRIEND_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address or password..
        /// </summary>
        public static string ServerResponse_BAD_LOGIN {
            get {
                return ResourceManager.GetString("ServerResponse_BAD_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot send a friend request to yourself..
        /// </summary>
        public static string ServerResponse_CANNOT_FRIEND_YOURSELF {
            get {
                return ResourceManager.GetString("ServerResponse_CANNOT_FRIEND_YOURSELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered email addresses don&apos;t match..
        /// </summary>
        public static string ServerResponse_EMAIL_ADDRESSES_DONT_MATCH {
            get {
                return ResourceManager.GetString("ServerResponse_EMAIL_ADDRESSES_DONT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already in use..
        /// </summary>
        public static string ServerResponse_EMAIL_ALREADY_IN_USE {
            get {
                return ResourceManager.GetString("ServerResponse_EMAIL_ALREADY_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a pending friend request towards this user..
        /// </summary>
        public static string ServerResponse_FRIEND_REQUEST_PENDING {
            get {
                return ResourceManager.GetString("ServerResponse_FRIEND_REQUEST_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something bad happened. Try again or ask in the forums or Discord if this issue persists..
        /// </summary>
        public static string ServerResponse_GENERAL_ERROR {
            get {
                return ResourceManager.GetString("ServerResponse_GENERAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is not valid..
        /// </summary>
        public static string ServerResponse_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("ServerResponse_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This password is empty or contains illegal characters..
        /// </summary>
        public static string ServerResponse_INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("ServerResponse_INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid username, only digits and letters allowed..
        /// </summary>
        public static string ServerResponse_INVALID_USERNAME {
            get {
                return ResourceManager.GetString("ServerResponse_INVALID_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server maintenance is ongoing, see https://forums.projectceleste.com/ for more information..
        /// </summary>
        public static string ServerResponse_MAINT_MODE {
            get {
                return ResourceManager.GetString("ServerResponse_MAINT_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to do that..
        /// </summary>
        public static string ServerResponse_METHOD_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ServerResponse_METHOD_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your launcher is outdated. Please update in order to login..
        /// </summary>
        public static string ServerResponse_OUTDATED_LAUNCHER {
            get {
                return ResourceManager.GetString("ServerResponse_OUTDATED_LAUNCHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered password is too short..
        /// </summary>
        public static string ServerResponse_PASSWORD_TOO_SHORT {
            get {
                return ResourceManager.GetString("ServerResponse_PASSWORD_TOO_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered passwords don&apos;t match..
        /// </summary>
        public static string ServerResponse_PASSWORDS_DOES_NOT_MATCH {
            get {
                return ResourceManager.GetString("ServerResponse_PASSWORDS_DOES_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your friend has too many friends and cannot receive your request..
        /// </summary>
        public static string ServerResponse_RECEIVER_HAS_TOO_MANY_FRIENDS {
            get {
                return ResourceManager.GetString("ServerResponse_RECEIVER_HAS_TOO_MANY_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration is disabled..
        /// </summary>
        public static string ServerResponse_REGISTRATION_DISABLED {
            get {
                return ResourceManager.GetString("ServerResponse_REGISTRATION_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must wait 3 minuets between each reset..
        /// </summary>
        public static string ServerResponse_RESET_AWAITING_COOLDOWN {
            get {
                return ResourceManager.GetString("ServerResponse_RESET_AWAITING_COOLDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been successfully reset.
        /// </summary>
        public static string ServerResponse_RESET_SUCCESS {
            get {
                return ResourceManager.GetString("ServerResponse_RESET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string ServerResponse_SUCCESS {
            get {
                return ResourceManager.GetString("ServerResponse_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have too many friends to accept new ones..
        /// </summary>
        public static string ServerResponse_TOO_MANY_FRIENDS {
            get {
                return ResourceManager.GetString("ServerResponse_TOO_MANY_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account was found with this email address..
        /// </summary>
        public static string ServerResponse_UNKNOWN_EMAIL {
            get {
                return ResourceManager.GetString("ServerResponse_UNKNOWN_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This verification key is unknown or not valid..
        /// </summary>
        public static string ServerResponse_UNKNOWN_VERIFICATION_KEY {
            get {
                return ResourceManager.GetString("ServerResponse_UNKNOWN_VERIFICATION_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user was not found..
        /// </summary>
        public static string ServerResponse_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ServerResponse_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is already taken..
        /// </summary>
        public static string ServerResponse_USERNAME_ALREADY_TAKEN {
            get {
                return ResourceManager.GetString("ServerResponse_USERNAME_ALREADY_TAKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while starting Age of Empires Online. Please try again or check the log files..
        /// </summary>
        public static string StartGameError {
            get {
                return ResourceManager.GetString("StartGameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celeste Fan Project Launcher is already compatible with Steam..
        /// </summary>
        public static string SteamConverterAlreadySteamGame {
            get {
                return ResourceManager.GetString("SteamConverterAlreadySteamGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string SteamConverterConfirmBtn {
            get {
                return ResourceManager.GetString("SteamConverterConfirmBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celeste Fan Project Launcher must be placed in the same folder has the Steam game files..
        /// </summary>
        public static string SteamConverterIncorrectInstallationDirectory {
            get {
                return ResourceManager.GetString("SteamConverterIncorrectInstallationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celeste Fan Project Launcher is now compatible with Steam. It will now re-start..
        /// </summary>
        public static string SteamConverterSuccess {
            get {
                return ResourceManager.GetString("SteamConverterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you want to start Celeste Fan Project Launcher when Age of Empires Online is started through Steam.
        /// </summary>
        public static string SteamConverterTitle {
            get {
                return ResourceManager.GetString("SteamConverterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Steam Conversion.
        /// </summary>
        public static string SteamConverterWindowTitle {
            get {
                return ResourceManager.GetString("SteamConverterWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string UnknownServerResponse {
            get {
                return ResourceManager.GetString("UnknownServerResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch changelog..
        /// </summary>
        public static string UpdateServiceChangelogError {
            get {
                return ResourceManager.GetString("UpdateServiceChangelogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Upnp device not found! &quot;UPnP Port Mapping&quot; has been disabled..
        /// </summary>
        public static string UPnPDisabledError {
            get {
                return ResourceManager.GetString("UPnPDisabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string WindowsFeatureHelperEnableBtn {
            get {
                return ResourceManager.GetString("WindowsFeatureHelperEnableBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string WindowsFeatureHelperEnabledStatus {
            get {
                return ResourceManager.GetString("WindowsFeatureHelperEnabledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string WindowsFeatureHelperFeatureInstalled {
            get {
                return ResourceManager.GetString("WindowsFeatureHelperFeatureInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install pending.
        /// </summary>
        public static string WindowsFeatureHelperFeatureIsPendingInstall {
            get {
                return ResourceManager.GetString("WindowsFeatureHelperFeatureIsPendingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported (unknow error).
        /// </summary>
        public static string WindowsFeatureHelperFeatureNotSupportedError {
            get {
                return ResourceManager.GetString("WindowsFeatureHelperFeatureNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially installed.
        /// </summary>
        public static string WindowsFeatureHelperFeaturePartiallyInstalled {
            get {
                return ResourceManager.GetString("WindowsFeatureHelperFeaturePartiallyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staged.
        /// </summary>
        public static string WindowsFeatureHelperFeatureStaged {
            get {
                return ResourceManager.GetString("WindowsFeatureHelperFeatureStaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported ({0}).
        /// </summary>
        public static string WindowsFeatureHelperFeatureUnsupported {
            get {
                return ResourceManager.GetString("WindowsFeatureHelperFeatureUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enabled.
        /// </summary>
        public static string WindowsFeatureHelperNotEnabledStatus {
            get {
                return ResourceManager.GetString("WindowsFeatureHelperNotEnabledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Feature Helper.
        /// </summary>
        public static string WindowsFeatureHelperTitle {
            get {
                return ResourceManager.GetString("WindowsFeatureHelperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string WindowsFeatureHelperUnknownStatus {
            get {
                return ResourceManager.GetString("WindowsFeatureHelperUnknownStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature can only be used on Windows 8 and later. Your are running {0}..
        /// </summary>
        public static string WindowsFeatureHelperUnsupportedOS {
            get {
                return ResourceManager.GetString("WindowsFeatureHelperUnsupportedOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string WindowsFirewallHelperApplication {
            get {
                return ResourceManager.GetString("WindowsFirewallHelperApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound.
        /// </summary>
        public static string WindowsFirewallHelperInbound {
            get {
                return ResourceManager.GetString("WindowsFirewallHelperInbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the launcher location..
        /// </summary>
        public static string WindowsFirewallHelperLauncherNotFound {
            get {
                return ResourceManager.GetString("WindowsFirewallHelperLauncherNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string WindowsFirewallHelperOpenBtn {
            get {
                return ResourceManager.GetString("WindowsFirewallHelperOpenBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbound.
        /// </summary>
        public static string WindowsFirewallHelperOutbound {
            get {
                return ResourceManager.GetString("WindowsFirewallHelperOutbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string WindowsFirewallHelperRuleInvalid {
            get {
                return ResourceManager.GetString("WindowsFirewallHelperRuleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string WindowsFirewallHelperRuleNotFound {
            get {
                return ResourceManager.GetString("WindowsFirewallHelperRuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string WindowsFirewallHelperRuleOpen {
            get {
                return ResourceManager.GetString("WindowsFirewallHelperRuleOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spartan.exe was not found, run a game scan to make sure you are not missing any game files..
        /// </summary>
        public static string WindowsFirewallHelperSpartanNotFound {
            get {
                return ResourceManager.GetString("WindowsFirewallHelperSpartanNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Firewall Helper.
        /// </summary>
        public static string WindowsFirewallHelperTitle {
            get {
                return ResourceManager.GetString("WindowsFirewallHelperTitle", resourceCulture);
            }
        }
    }
}
