//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Celeste_Launcher_Gui.StringResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MLStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MLStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Celeste_Launcher_Gui.StringResources.MLStrings", typeof(MLStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password value and confirm password value don&apos;t match!.
        /// </summary>
        internal static string srtPasswordConfirmNotMatch {
            get {
                return ResourceManager.GetString("srtPasswordConfirmNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already logged-in or logged-in in progress!.
        /// </summary>
        internal static string strAlreadyLoged {
            get {
                return ResourceManager.GetString("strAlreadyLoged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to close the game first!.
        /// </summary>
        internal static string strCloseGameFirst {
            get {
                return ResourceManager.GetString("strCloseGameFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string strEMail {
            get {
                return ResourceManager.GetString("strEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Timeout!.
        /// </summary>
        internal static string strErrorTimeout {
            get {
                return ResourceManager.GetString("strErrorTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game already runing!.
        /// </summary>
        internal static string strGameAlreadyRunning {
            get {
                return ResourceManager.GetString("strGameAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email!.
        /// </summary>
        internal static string strInvalidEmail {
            get {
                return ResourceManager.GetString("strInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Invite Code!.
        /// </summary>
        internal static string strInvalidInviteCode {
            get {
                return ResourceManager.GetString("strInvalidInviteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password minimum length is 8 char, maximum length is 32 char!.
        /// </summary>
        internal static string strInvalidPassordLength {
            get {
                return ResourceManager.GetString("strInvalidPassordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name, only letters and digits allowed, minimum length is 3 char and maximum length is 15 char!.
        /// </summary>
        internal static string strInvalidUserName {
            get {
                return ResourceManager.GetString("strInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in!.
        /// </summary>
        internal static string strNotLoggedIn {
            get {
                return ResourceManager.GetString("strNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed with success..
        /// </summary>
        internal static string strPasswordChanged {
            get {
                return ResourceManager.GetString("strPasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password maximum length is 32 char!.
        /// </summary>
        internal static string strPasswordMaxLength {
            get {
                return ResourceManager.GetString("strPasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password minimum length is 8 char!.
        /// </summary>
        internal static string strPasswordMinimunLength {
            get {
                return ResourceManager.GetString("strPasswordMinimunLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password value and confirm new password value don&apos;t match!.
        /// </summary>
        internal static string strPasswordsNotMatch {
            get {
                return ResourceManager.GetString("strPasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string strRank {
            get {
                return ResourceManager.GetString("strRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registred with success..
        /// </summary>
        internal static string strRegisteredSuccess {
            get {
                return ResourceManager.GetString("strRegisteredSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connection timeout (&gt; 20sec)!.
        /// </summary>
        internal static string strServerConectionTimeot {
            get {
                return ResourceManager.GetString("strServerConectionTimeot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Offline.
        /// </summary>
        internal static string strServerOffline {
            get {
                return ResourceManager.GetString("strServerOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server response timeout (&gt; 20sec)!.
        /// </summary>
        internal static string strServerResponseTimeot {
            get {
                return ResourceManager.GetString("strServerResponseTimeot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Upnp device not found! Set &quot;Port mapping&quot; to manual in &quot;Mp Settings&quot; and configure your router..
        /// </summary>
        internal static string strUpnpDeviceNotFound {
            get {
                return ResourceManager.GetString("strUpnpDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string strUserName {
            get {
                return ResourceManager.GetString("strUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been disconnected from the server!.
        /// </summary>
        internal static string strYouHaveBeenDisconnected {
            get {
                return ResourceManager.GetString("strYouHaveBeenDisconnected", resourceCulture);
            }
        }
    }
}
